//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int Folio { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public int Rut { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CantidadMuestras { get; set; }
    }
}
